---
- name: Terminate EC2 instances 
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - amazon.aws

  vars_files:
    - ../vault/secrets.yml

  tasks:

    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../vars/aws.yml

    - ansible.builtin.include_role:
        name: ../roles/aws_ec2_instance
        tasks_from: ec2_terminate_rhel.yml
      when: aws_host_os == 'rhel9'


    - ansible.builtin.include_role:
        name: ../roles/aws_ec2_instance
        tasks_from: ec2_terminate_win.yml
      when: aws_host_os == 'win2022'
